// Data Event dan Pemateri Sahabat Belajar
const appData = {
  pemateri: [
    {
      id: 1,
      nama: "Kak Nadya Pendongeng Ceria",
      gambar: "img\\pemateri\\nadya.jpg",
      linkCv: "#",
      lokasi: "Sidoarjo",
      tag: ["Pendongeng", "Storyteller", "MC"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 15,
    },
    {
      id: 2,
      nama: "Kak Fatin dan Boneka Fatan",
      gambar: "img\\pemateri\\fatin.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Pendongeng"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 12,
    },
    {
      id: 3,
      nama: "Kak Halisah dan Boneka Nara",
      gambar: "img\\pemateri\\halisah.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Pendongeng"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 18,
    },
    {
      id: 4,
      nama: "Kak Ziyah dan Boneka Zizi",
      gambar: "img\\pemateri\\ziyah.jpg",
      linkCv: "#",
      lokasi: "Sidoarjo",
      tag: ["Pendongeng"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 20,
    },
    {
      id: 5,
      nama: "Kak Sari dan Boneka Sarah",
      gambar: "img\\pemateri\\sari.jpg",
      linkCv: "#",
      lokasi: "Sidoarjo",
      tag: ["Pendongeng"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 10,
    },
    {
      id: 6,
      nama: "Ustadz Muhammad Thufail Hilmi Daffa S.Ag",
      gambar: "img\\pemateri\\daffa.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 14,
    },
    {
      id: 7,
      nama: "Ustadz Muhammad Fikri Amruddin",
      gambar: "img\\pemateri\\fikri.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 16,
    },
    {
      id: 8,
      nama: "Ustadz Mochamad As'ad Ihsan",
      gambar: "img\\pemateri\\asad.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
    {
      id: 9,
      nama: "Ustadz Abul A'la Al-Maududi",
      gambar: "img\\pemateri\\abul.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
    {
      id: 10,
      nama: "Ustadz Mohamad Zahron Afifudin, S.Sos",
      gambar: "img\\pemateri\\zahron.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
    {
      id: 11,
      nama: "Ustadzah Nur Hidayati S, M.Ag",
      gambar: "img\\pemateri\\hida.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
    {
      id: 12,
      nama: "Ustadzah Nadya Sofia Putri, S.Ag",
      gambar: "img\\pemateri\\nadya2.jpg",
      linkCv: "#",
      lokasi: "Sidoarjo",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
  ],

  events: [
    {
      id: 1,
      nama: "Talkshow Online Strategi Jitu Tembus Beasiswa LPDP",
      gambar: "img\\event\\talkshow-2024-1.jpg",
      linkIg: "https://www.instagram.com/p/DDPgHxsyPSK/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "Online via Google Meet",
      tanggal: "14 Desember 2024",
      waktu: "20:00 - 21:30 WIB",
      pemateri: ["Khairul Atfal S.Ag (Awardee LPDP Kemenkeu 2024)"],
      tag: ["talkshow", "beasiswa", "lpdp"],
      kategori: "talkshow",
      deskripsi: "Ingin lolos beasiswa LPDP? Temukan rahasia dan strategi sukses langsung dari awardee berpengalaman! Wujudkan impian pendidikan Anda bersama kami di talkshow inspiratif ini. Jangan lewatkan kesempatan emas untuk mewujudkan cita-cita Anda!",
    },
    {
      id: 2,
      nama: "Talkshow Online Ventriloquist Boneka Menarik Minat Anak dengan Bercerita",
      gambar: "img\\event\\talkshow-2025-1.jpg",
      linkIg: "https://www.instagram.com/p/DFDLlM_yvx_/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "Online via Google Meet",
      tanggal: "26 Januari 2025",
      waktu: "09:00 - 11:00 WIB",
      pemateri: ["Kak Nadya Sofia Putri, S.Ag (Pendongeng Ceria Jawa Timur)"],
      tag: ["talkshow", "ventriloquist", "boneka"],
      kategori: "talkshow",
      deskripsi: "Ayo temukan cara seru dan kreatif menarik perhatian anak lewat seni bercerita bersama pendongeng inspiratif! Dapatkan wawasan menarik dan pengalaman baru untuk mendukung perjalanan pendidikan si buah hati. Kesempatan langka ini sayang untuk dilewatkan!",
    },
    {
      id: 3,
      nama: "Literasi Keliling Goes to School",
      gambar: "img\\event\\litkel-2026-15-2.jpg",
      linkIg: "https://www.instagram.com/p/DTcM_HvEpkr/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "SMK Al-Ishlah Surabaya",
      tanggal: "15 Januari 2026",
      waktu: "09:00 - 10:00 WIB",
      pemateri: ["Ustadz Thufail Hilmi Daffa, S.Ag"],
      tag: ["dakwah", "literasi"],
      kategori: "dakwah",
      deskripsi: "Ayo ramaikan Literasi Keliling Goes to School bersama Ustadz Thufail Hilmi Daffa, S.Ag! Dapatkan pengalaman seru dan inspiratif dengan dakwah yang membangkitkan semangat literasi di sekolah. Jangan lewatkan momen kebersamaan penuh wawasan, tawa, dan motivasi untuk menumbuhkan budaya membaca serta karakter positif. Ajak teman-temanmu untuk belajar, berbagi, dan beraksi bersama dalam kegiatan penuh makna ini!",
    },
    {
      id: 4,
      nama: "Literasi Keliling Goes to School",
      gambar: "img\\event\\litkel-2026-15.jpg",
      linkIg: "https://www.instagram.com/p/DTe3MQXEnFv/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "PG/TK Subulus Salam",
      tanggal: "15 Januari 2026",
      waktu: "08:00 - 09:00 WIB",
      pemateri: ["Kak Sari dan Boneka Sarah"],
      tag: ["dongeng", "literasi"],
      kategori: "dongeng",
      deskripsi: "Yuk, ikuti petualangan seru Dongeng Anak Ceria bersama Kak Sari dan Boneka Sarah! Rasakan pengalaman belajar yang penuh tawa, imajinasi, dan inspirasi langsung di sekolahmu. Jangan lewatkan momen spesial ini ajak teman-temanmu untuk menikmati dongeng menarik yang akan membuat literasi jadi makin menyenangkan!",
    },
    {
      id: 5,
      nama: "Literasi Keliling Goes to School",
      gambar: "img\\event\\litkel-2026-17.jpg",
      linkIg: "https://www.instagram.com/p/DTcNhnkkpUG/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "SDN Junwangi Krian",
      tanggal: "17 Januari 2026",
      waktu: "08:00 - 09:00 WIB",
      pemateri: ["Kak Ziyah dan Boneka Zizi"],
      tag: ["dongeng", "literasi"],
      kategori: "dongeng",
      deskripsi: "Ajak teman-temanmu menyambut kisah seru Dongeng Anak Ceria bersama Kak Ziyah dan Boneka Zizi! Nikmati pembelajaran kreatif, penuh keceriaan, dan berimajinasi langsung dari sekolah. Jangan lewatkan kesempatan penuh inspirasi ini untuk menjadikan literasi semakin menyenangkan dan berkesan bagi semua peserta!",
    },
    {
      id: 6,
      nama: "Literasi Keliling Goes to School",
      gambar: "img\\event\\litkel-2026-17-2.jpg",
      linkIg: "https://www.instagram.com/p/DTe3eWpkgxJ/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "SDN Waung",
      tanggal: "17 Januari 2026",
      waktu: "08:00 - 09:00 WIB",
      pemateri: ["Kak Sari dan Boneka Sarah"],
      tag: ["dongeng", "literasi"],
      kategori: "dongeng",
      deskripsi: "Ayo meriahkan Dongeng Anak Ceria bersama Kak Sari dan Boneka Sarah! Dapatkan suasana belajar penuh keceriaan, kreativitas, dan inspirasi langsung di sekolahmu. Jangan sampai terlewat—ajak teman-temanmu untuk menikmati kisah seru yang membuat literasi semakin asyik dan berkesan!",
    },
    {
      id: 7,
      nama: "Literasi Keliling Goes to School",
      gambar: "img\\event\\litkel-2026-19-2.jpg",
      linkIg: "https://www.instagram.com/p/DTe2npSkg99/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "Yayasan Maryam Surabaya",
      tanggal: "19 Januari 2026",
      waktu: "09:00 - 10:00 WIB",
      pemateri: ["Ustadz Thufail Hilmi Daffa, S.Ag"],
      tag: ["dakwah", "literasi"],
      kategori: "dakwah",
      deskripsi: "Ayo ramaikan Literasi Keliling Goes to School bersama Ustadz Thufail Hilmi Daffa, S.Ag! Dapatkan pengalaman seru dan inspiratif dengan dakwah yang membangkitkan semangat literasi di sekolah. Jangan lewatkan momen kebersamaan penuh wawasan, tawa, dan motivasi untuk menumbuhkan budaya membaca serta karakter positif. Ajak teman-temanmu untuk belajar, berbagi, dan beraksi bersama dalam kegiatan penuh makna ini!",
    },
    {
      id: 8,
      nama: "Literasi Keliling Goes to School",
      gambar: "img\\event\\litkel-2026-19.jpg",
      linkIg: "https://www.instagram.com/p/DTe3ritEtpI/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "TK Kartini",
      tanggal: "19 Januari 2026",
      waktu: "08:30 - 09:30 WIB",
      pemateri: ["Kak Sari dan Boneka Sarah"],
      tag: ["dongeng", "literasi"],
      kategori: "dongeng",
      deskripsi: "Yuk, ikuti petualangan seru Dongeng Anak Ceria bersama Kak Sari dan Boneka Sarah! Rasakan pengalaman belajar yang penuh tawa, imajinasi, dan inspirasi langsung di sekolahmu. Jangan lewatkan momen spesial ini—ajak teman-temanmu untuk menikmati dongeng menarik yang akan membuat literasi jadi makin menyenangkan!",
    },
    {
      id: 9,
      nama: "Literasi Keliling Goes to School",
      gambar: "img\\event\\litkel-2026-20.jpg",
      linkIg: "https://www.instagram.com/p/DTe4VOLkuz9/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "SDN Pakis 3 Surabaya",
      tanggal: "20 Januari 2026",
      waktu: "09:30 - 10:30 WIB",
      pemateri: ["Ustadz Muhammad Fikri Amruddin"],
      tag: ["dakwah", "literasi"],
      kategori: "dakwah",
      deskripsi: "Ayo ramaikan Literasi Keliling Goes to School bersama Ustadz Muhammad Fikri Amruddin! Dapatkan pengalaman seru dan inspiratif dengan dakwah yang membangkitkan semangat literasi di sekolah. Jangan lewatkan momen kebersamaan penuh wawasan, tawa, dan motivasi untuk menumbuhkan budaya membaca serta karakter positif. Ajak teman-temanmu untuk belajar, berbagi, dan beraksi bersama dalam kegiatan penuh makna ini!",
    },
    {
      id: 10,
      nama: "Talkshow Online Berdakwah dengan Cerita",
      gambar: "img\\event\\talkshow-2026-1.jpg",
      linkIg: "https://www.instagram.com/p/DUCDwO9kqDI/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "Online via Google Meet",
      tanggal: "1 Februari 2026",
      waktu: "09:00 - 11:00 WIB",
      pemateri: ["Kak Nadya Sofia Putri, S.Ag (Pendongeng Ceria Jawa Timur)", "Kak Ahmad Agung Ferrianto (Pendongeng Nasional)"],
      tag: ["talkshow", "pendongeng"],
      kategori: "talkshow",
      deskripsi: "Yuk, cari tahu berbagai trik seru dan kreatif untuk memikat perhatian anak bersama para pendongeng inspiratif! Raih wawasan segar dan pengalaman berharga yang bisa menunjang pendidikan dan perkembangan sang buah hati. Jangan lewatkan momen spesial ini—siapkan diri untuk inspirasi dan pengalaman berbeda yang sayang untuk dilewatkan!",
    },
  ],
};

// Export untuk module system
if (typeof module !== "undefined" && module.exports) {
  module.exports = appData;
}
