// Data Event dan Pemateri Sahabat Belajar
const appData = {
  events: [
    {
      id: 1,
      nama: "Talkshow Online Strategi Jitu Tembus Beasiswa LPDP",
      gambar: "img\\event\\talkshow-2024-1.jpg",
      linkIg: "https://www.instagram.com/p/DDPgHxsyPSK/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "Online via Google Meet",
      tanggal: "14 Desember 2024",
      waktu: "20:00 - 21:30 WIB",
      pemateri: ["Khairul Atfal S.Ag (Awardee LPDP Kemenkeu 2024)"],
      tag: ["talkshow", "beasiswa", "lpdp"],
      kategori: "talkshow",
      deskripsi: "Ingin lolos beasiswa LPDP? Temukan rahasia dan strategi sukses langsung dari awardee berpengalaman! Wujudkan impian pendidikan Anda bersama kami di talkshow inspiratif ini. Jangan lewatkan kesempatan emas untuk mewujudkan cita-cita Anda!",
    },
    {
      id: 2,
      nama: "Talkshow Online Ventriloquist Boneka Menarik Minat Anak dengan Bercerita",
      gambar: "img\\event\\talkshow-2025-1.jpg",
      linkIg: "https://www.instagram.com/p/DFDLlM_yvx_/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      lokasi: "Online via Google Meet",
      tanggal: "26 Januari 2025",
      waktu: "09:00 - 11:00 WIB",
      pemateri: ["Kak Nadya Sofia Putri, S.Ag (Pendongeng Ceria Jawa Timur)"],
      tag: ["talkshow", "ventriloquist", "boneka"],
      kategori: "talkshow",
      deskripsi: "Ayo temukan cara seru dan kreatif menarik perhatian anak lewat seni bercerita bersama pendongeng inspiratif! Dapatkan wawasan menarik dan pengalaman baru untuk mendukung perjalanan pendidikan si buah hati. Kesempatan langka ini sayang untuk dilewatkan!",
    },
    {
      id: 3,
      nama: "Hackathon Sahabat Belajar",
      gambar: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800",
      linkIg: "https://instagram.com/sahabatbelajar",
      lokasi: "Online & Onsite",
      tanggal: "1 Maret 2026",
      waktu: "48 Jam Non-Stop",
      pemateri: ["Ahmad Rizki", "Siti Nurhaliza", "Budi Santoso"],
      tag: ["hackathon", "competition", "coding"],
      kategori: "hackathon",
      deskripsi: "Kompetisi coding 48 jam untuk mengasah skill dan berkolaborasi dengan developer lainnya. Hadiah total puluhan juta rupiah menanti!",
    },
    {
      id: 4,
      nama: "Workshop Mobile Development",
      gambar: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800",
      linkIg: "https://instagram.com/sahabatbelajar",
      lokasi: "Online via Google Meet",
      tanggal: "8 Maret 2026",
      waktu: "09:00 - 17:00 WIB",
      pemateri: ["Dewi Lestari"],
      tag: ["workshop", "mobile-development", "react-native", "flutter"],
      kategori: "workshop",
      deskripsi: "Pelajari pengembangan aplikasi mobile menggunakan React Native dan Flutter. Dari konsep hingga deployment ke Play Store dan App Store.",
    },
    {
      id: 5,
      nama: "Workshop Data Science",
      gambar: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
      linkIg: "https://instagram.com/sahabatbelajar",
      lokasi: "Online via Google Meet",
      tanggal: "15 Maret 2026",
      waktu: "09:00 - 17:00 WIB",
      pemateri: ["Siti Nurhaliza"],
      tag: ["workshop", "data-science", "python", "machine-learning"],
      kategori: "workshop",
      deskripsi: "Pelajari data science dari dasar hingga advanced. Menggunakan Python, pandas, dan machine learning untuk analisis data yang powerful.",
    },
    {
      id: 6,
      nama: "Tech Meetup Jakarta",
      gambar: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800",
      linkIg: "https://instagram.com/sahabatbelajar",
      lokasi: "Co-working Space Jakarta",
      tanggal: "22 Maret 2026",
      waktu: "18:00 - 21:00 WIB",
      pemateri: ["Maya Sari", "Andi Wijaya"],
      tag: ["networking", "meetup", "tech"],
      kategori: "networking",
      deskripsi: "Meetup bulanan untuk developer dan tech enthusiast. Diskusi tentang teknologi terbaru, sharing pengalaman, dan networking.",
    },
  ],
  pemateri: [
    {
      id: 1,
      nama: "Kak Nadya Pendongeng Ceria",
      gambar: "img\\pemateri\\nadya.jpg",
      linkCv: "#",
      lokasi: "Sidoarjo",
      tag: ["Pendongeng", "Storyteller", "MC"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 15,
    },
    {
      id: 2,
      nama: "Kak Fatin dan Boneka Fatan",
      gambar: "img\\pemateri\\fatin.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Pendongeng"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 12,
    },
    {
      id: 3,
      nama: "Kak Halisah dan Boneka Nara",
      gambar: "img\\pemateri\\halisah.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Pendongeng"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 18,
    },
    {
      id: 4,
      nama: "Kak Ziyah dan Boneka Zizi",
      gambar: "img\\pemateri\\ziyah.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Pendongeng"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 20,
    },
    {
      id: 5,
      nama: "Kak Sari dan Boneka Sarah",
      gambar: "img\\pemateri\\sari.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Pendongeng"],
      posisi: "Pendongeng",
      deskripsi: "",
      workshop: 10,
    },
    {
      id: 6,
      nama: "Ustadz Muhammad Thufail Hilmi Daffa S.Ag",
      gambar: "img\\pemateri\\daffa.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 14,
    },
    {
      id: 7,
      nama: "Ustadz Muhammad Fikri Amruddin",
      gambar: "img\\pemateri\\fikri.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 16,
    },
    {
      id: 8,
      nama: "Ustadz Mochamad As'ad Ihsan",
      gambar: "img\\pemateri\\asad.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
    {
      id: 9,
      nama: "Ustadz Abul A'la Al-Maududi",
      gambar: "img\\pemateri\\abul.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
    {
      id: 10,
      nama: "Ustadz Mohamad Zahron Afifudin, S.Sos",
      gambar: "img\\pemateri\\zahron.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
    {
      id: 11,
      nama: "Ustadzah Nur Hidayati S, M.Ag",
      gambar: "img\\pemateri\\hida.jpg",
      linkCv: "#",
      lokasi: "Surabaya",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
    {
      id: 12,
      nama: "Ustadzah Nadya Sofia Putri, S.Ag",
      gambar: "img\\pemateri\\nadya2.jpg",
      linkCv: "#",
      lokasi: "Sidoarjo",
      tag: ["Dakwah"],
      posisi: "Pendakwah",
      deskripsi: "",
      workshop: 8,
    },
  ],
};

// Export untuk module system
if (typeof module !== "undefined" && module.exports) {
  module.exports = appData;
}
